import type {
  ActivityRecord,
  AIRequestRecord,
  CustomFieldDefinitionRecord,
  CustomFieldValueRecord,
  AttachmentRecord,
  AutomationSettingsRecord,
  BlogPostRecord,
  CampaignRecord,
  CaseStudyRecord,
  ClientRecord,
  DashboardSummary,
  FinancialRecord,
  FAQRecord,
  LeadRecord,
  MethodologyContentRecord,
  MessageRecord,
  ProofAssetsContentRecord,
  ProposalRecord,
  ProjectListRecord,
  ProjectRecord,
  ServiceRecord,
  SiteSettingsRecord,
  TaskRecord,
  TaskChecklistItemRecord,
  TaskCommentRecord,
  TaskDependencyRecord,
  TestimonialRecord,
  UserRecord,
  UserSession,
  WorkTemplateRecord,
  WorkspaceRecord,
} from "@/lib/types";
import { BRAND_COMPANY_NAME } from "@/lib/brand";
import { defaultSectorCatalog } from "@/lib/sector-content";

export const demoAdminUser: UserSession = {
  id: "user_admin_1",
  name: "Joice Martins",
  email: "admin@agencia-premium.com",
  role: "ADMIN",
};

export const demoAccountManagerUser: UserSession = {
  id: "user_manager_1",
  name: "Caio Martins",
  email: "caio@atlasgrowth.studio",
  role: "ACCOUNT_MANAGER",
};

export const demoSettings: SiteSettingsRecord = {
  agencyName: "Ameni",
  heroTitle: "Amenize a complexidade potencialize seus resultados",
  heroSubtitle:
    "A Ameni conduz tráfego pago, orgânico, social media, conteúdo, web e posicionamento para transformar marketing em uma operação mais clara, elegante e orientada a resultado.",
  primaryCta: "Solicitar diagnóstico",
  secondaryCta: "Agendar reunião",
  email: "contato@atlasgrowth.studio",
  phone: "+55 11 4000-1234",
  whatsapp: "+55 11 98888-0000",
  calendarUrl: "",
  calendarEmbedUrl: "",
  instagramUrl: "https://instagram.com/atlasgrowth.studio",
  linkedinUrl: "https://linkedin.com/company/atlas-growth-studio",
};

export const demoServices: ServiceRecord[] = [
  {
    id: "svc_1",
    name: "Gestão de tráfego pago",
    slug: "gestao-de-trafego-pago",
    description: "Planejamento de canais, setup técnico, rotina de otimização e leitura executiva.",
    benefit: "Mais previsibilidade de aquisição e controle de CAC.",
    featured: true,
  },
  {
    id: "svc_2",
    name: "Landing pages e CRO",
    slug: "landing-pages-e-cro",
    description: "Páginas de alta conversão, testes de oferta e melhoria contínua da jornada.",
    benefit: "Mais conversão sem necessariamente aumentar investimento.",
    featured: true,
  },
  {
    id: "svc_3",
    name: "Criativos e estratégia digital",
    slug: "criativos-e-estrategia-digital",
    description: "Criativos, ganchos, ofertas e direcionamento por etapa do funil.",
    benefit: "Mensagens mais fortes e campanhas com maior aderência.",
  },
  {
    id: "svc_4",
    name: "Social media e operação de conteúdo",
    slug: "funis-e-automacao-comercial",
    description: "Planejamento editorial, produção criativa, rotina de publicação e leitura executiva do que está gerando resposta.",
    benefit: "Marca mais presente, operação mais consistente e comunicação mais alinhada ao comercial.",
  },
];

export const demoTestimonials: TestimonialRecord[] = [
  {
    id: "test_1",
    authorName: "Marina Torres",
    role: "CEO",
    company: "Derma Prime Clinic",
    quote:
      "A agência organizou nossa captação premium, reduziu o CPL e nos deu um processo comercial muito mais claro.",
    featured: true,
  },
  {
    id: "test_2",
    authorName: "Carlos Mendes",
    role: "Diretor Comercial",
    company: "MoveFit Studios",
    quote:
      "Não foi só tráfego. Houve melhoria de oferta, mensagens, páginas e follow-ups. Virou uma máquina mais consistente.",
  },
  {
    id: "test_3",
    authorName: "Beatriz Nogueira",
    role: "Sócia",
    company: "Nogueira Interiores",
    quote:
      "A Ameni trouxe visibilidade, ritmo de execução e uma operação muito mais organizada entre campanha, conteúdo e comercial.",
  },
];

export const demoCaseStudies: CaseStudyRecord[] = [
  {
    id: "case_1",
    slug: "clinica-premium-com-agenda-mais-previsivel",
    title: "Clínica premium com agenda mais previsível",
    niche: "Estética",
    challenge: "Leads inconsistentes e excesso de dependência de indicação.",
    solution: "Reposicionamento da oferta, criativos novos, landing page e rotina comercial mais bem estruturada.",
    result: "CPL 31% menor e aumento de 42% em consultas agendadas.",
    metrics: {
      consultas: "+42%",
      cpl: "-31%",
      show_rate: "+18%",
    },
    featured: true,
  },
  {
    id: "case_2",
    slug: "loteamento-de-medio-alto-padrao-com-leads-qualificados",
    title: "Loteamento de médio-alto padrão com leads qualificados",
    niche: "Imobiliário",
    challenge: "Muito volume com pouca qualidade para o time de vendas.",
    solution: "Segmentação refinada, páginas por intenção e follow-up consultivo por etapa.",
    result: "Melhora na qualificação e 2,6x mais oportunidades reais.",
    metrics: {
      oportunidades: "2,6x",
      taxa_reuniao: "+37%",
    },
  },
];

export const demoFaqs: FAQRecord[] = [
  {
    id: "faq_1",
    question: "Em quanto tempo os resultados costumam aparecer?",
    answer:
      "Nos primeiros 30 dias estruturamos conta, dados, criativos e páginas. Ganhos mais consistentes costumam ser percebidos entre 45 e 90 dias.",
    order: 1,
  },
  {
    id: "faq_2",
    question: "Vocês atuam só com mídia paga?",
    answer:
      "Não. A Ameni pode atuar com tráfego pago, orgânico, social media, criativos, vídeo, landing pages e posicionamento, conforme o momento da marca.",
    order: 2,
  },
  {
    id: "faq_3",
    question: "A agência atende negócios high-ticket?",
    answer:
      "Sim. A operação foi desenhada para serviços, clínicas, mercado imobiliário, educação premium e negócios com ciclo comercial mais consultivo.",
    order: 3,
  },
];

export const demoBlogPosts: BlogPostRecord[] = [
  {
    id: "blog_1",
    title: "Como reduzir CPL sem sacrificar qualidade do lead",
    slug: "como-reduzir-cpl-sem-sacrificar-qualidade",
    excerpt: "Os ajustes que mais movem ponteiros quando o problema nao e so a campanha, mas a oferta e a jornada.",
    content:
      "Quando o CPL sobe, o primeiro impulso costuma ser mexer em segmentacao, criativo ou verba. Isso faz sentido, mas quase nunca resolve o problema sozinho.\n\nEm operacoes mais maduras, o custo por lead e um reflexo do conjunto: oferta, promessa, criativo, pagina, velocidade do time comercial e experiencia depois do clique. Se a campanha ate atrai atencao, mas a jornada nao sustenta confianca, o algoritmo sente e a eficiencia piora.\n\nO primeiro passo e revisar se a promessa da campanha esta alinhada com o nivel de desejo e maturidade do publico. Muitas marcas anunciam com uma promessa generica e acabam comprando cliques curiosos em vez de demanda qualificada.\n\nDepois disso, vale olhar para a pagina. Uma landing page premium precisa reduzir friccao, elevar percepcao de valor e deixar claro qual e o proximo passo. Quando a experiencia de conversao melhora, o canal responde com mais eficiencia sem necessariamente pedir mais investimento.\n\nOutro ponto decisivo e o retorno comercial. Se o lead chega e encontra demora, abordagem fraca ou falta de contexto, a conta inteira perde potencia. Em muitos cenarios, melhorar follow-up gera mais impacto no resultado do que qualquer ajuste isolado de campanha.\n\nReduzir CPL com criterio nao significa comprar lead barato. Significa comprar atencao certa, conduzir melhor a jornada e transformar investimento em oportunidade real.",
    category: "Performance",
    publishedAt: "2026-02-12T09:00:00.000Z",
  },
  {
    id: "blog_2",
    title: "O que uma agencia premium precisa mostrar no primeiro atendimento",
    slug: "o-que-uma-agencia-premium-precisa-mostrar",
    excerpt: "Estrutura comercial, narrativa e provas que aumentam conversao de diagnostico para proposta.",
    content:
      "O primeiro atendimento de uma agencia premium nao pode parecer improvisado. Ele precisa transmitir leitura de negocio, clareza comercial e maturidade operacional desde o inicio.\n\nAntes de vender servicos, a agencia precisa mostrar que entende o estagio da empresa, o tipo de demanda que ela quer atrair e os gargalos que hoje travam crescimento. Isso muda completamente a percepcao da conversa.\n\nOutro ponto importante e a narrativa. Marcas de alto valor nao compram apenas execucao; elas compram seguranca. Quando a agencia explica o processo com clareza, apresenta recortes de casos semelhantes e traduz estrategia em proximos passos objetivos, a venda acontece em um nivel mais consultivo.\n\nA prova tambem precisa ser bem escolhida. Nao basta empilhar numero. O que converte melhor e mostrar contexto: qual era o problema, o que foi feito, o que mudou em demanda, percepcao ou venda.\n\nPor fim, o atendimento premium mostra organizacao. Um follow-up bem escrito, uma proposta coerente e um ritmo claro de comunicacao reforcam aquilo que foi prometido na call. Em outras palavras, a venda comeca antes da assinatura e a experiencia precisa sustentar o ticket desejado.",
    category: "Comercial",
    publishedAt: "2026-02-24T09:00:00.000Z",
  },
];

export const demoMethodologyContent: MethodologyContentRecord = {
  heroEyebrow: "Metodologia",
  heroTitle: "Um método para reduzir complexidade, organizar prioridades e transformar marketing em resultado.",
  heroDescription:
    "Nosso método combina leitura de negócio, criação com critério, execução disciplinada e melhoria contínua para transformar marketing em resultado consistente.",
  heroAside:
    "A metodologia existe para evitar o erro mais comum de operacoes digitais: anuncios desconectados da marca, conteudo desconectado do comercial e uma experiencia digital que nao sustenta o valor vendido.",
  processTitle: "Como a metodologia se traduz em execução real.",
  processDescription:
    "Esse processo foi desenhado para aumentar qualidade de decisao, ritmo operacional e coerencia entre marca e resultado.",
  impactEyebrow: "O que muda na pratica",
  impactTitle: "Menos canais soltos. Mais direção.",
  impactBody: [
    "Quando a metodologia entra, o marketing deixa de ser uma soma de tarefas e passa a operar como estrutura: oferta mais clara, criativos melhores, paginas mais coerentes, social com direcao, SEO com funcao e uma rotina comercial com mais contexto.",
    "Esse tipo de integracao aumenta eficiencia, melhora valor percebido e cria base para escalar com menos improviso.",
  ],
  ctaTitle: "Quer aplicar essa metodologia no seu contexto comercial?",
  ctaDescription:
    "Se fizer sentido, abrimos o diagnostico pela sua fase atual e mostramos onde performance, conteudo, web e marca devem entrar primeiro.",
  pillars: [
    {
      title: "Diagnostico orientado a negocio",
      description:
        "Entramos pelo contexto comercial antes de discutir canais. Ticket, ciclo de venda, objecoes e gargalos guiam a estrategia.",
    },
    {
      title: "Performance com narrativa",
      description:
        "Midia paga e CRO operam junto com copy, prova, oferta e paginas para reduzir desperdicio e elevar resposta.",
    },
    {
      title: "Organico como ativo",
      description:
        "SEO, blog e presenca de busca constroem base proprietaria para que a marca dependa menos de compra constante de alcance.",
    },
    {
      title: "Video e criacao com funcao",
      description:
        "Roteiro, captacao, motion e cortes sao pensados para prender atencao, reforcar percepcao e apoiar conversao.",
    },
    {
      title: "Ritmo operacional",
      description:
        "SLA, backlog, feedback e leitura executiva garantem velocidade de execucao sem perder qualidade de decisao.",
    },
    {
      title: "Integracao real entre frentes",
      description:
        "Branding, social, web, video e midia deixam de disputar prioridade e passam a responder ao mesmo plano de crescimento.",
    },
  ],
};

export const demoProofAssetsContent: ProofAssetsContentRecord = {
  eyebrow: "Prova visual",
  title: "Não mostramos só frases bonitas. Mostramos estratégia, criação e leitura de operação.",
  description:
    "A prova social mais forte para uma agência premium não é apenas o depoimento. É a combinação entre contexto, captura de resultado, criativo e experiência digital.",
  logos: ["Nova Med", "Orion Prime", "Haus Capital", "Clarear Educacao", "Vista Health"],
  features: [
    {
      title: "Relatórios executivos",
      description: "CAC, CPL, show rate, receita e sinais de funil traduzidos pela Ameni em decisão.",
    },
    {
      title: "Criativos orientados à resposta",
      description: "Reels, VSLs curtas, UGC premium e anúncios com critério de conversão.",
    },
    {
      title: "Landing pages de campanha",
      description: "Estruturas com prova, oferta, narrativa e UX desenhadas para captar.",
    },
  ],
  mockupEyebrow: "Mockup operacional",
  mockupTitle: "Leitura de crescimento em uma unica composicao.",
  mockupMetrics: [
    { value: "+42%", label: "agenda" },
    { value: "-31%", label: "CPL" },
    { value: "+18%", label: "show rate" },
  ],
  mockupBars: [
    { label: "Meta Ads", width: "78%" },
    { label: "Landing page", width: "64%" },
    { label: "Follow-up comercial", width: "86%" },
  ],
  creativeEyebrow: "Hook premium",
  creativeTitle: "Atencao certa antes do clique certo.",
  creativeDescription: "Roteiro curto, frame forte e CTA alinhado com valor percebido.",
  landingEyebrow: "Oferta / prova / CTA",
  landingHighlight: "Estruturas com narrativa e UX para captar demanda com mais clareza.",
};

export const demoLeads: LeadRecord[] = [
  {
    id: "lead_1",
    name: "Luciana Araujo",
    email: "luciana@clinicabellavita.com",
    phone: "+55 11 99999-1111",
    company: "Clinica Bella Vita",
    niche: "Estetica",
    contactPreference: "Reuniao estrategica",
    serviceInterest: "Trafego Pago",
    urgency: "30-dias",
    objective: "Aumentar agenda de procedimentos premium",
    message: "Quero mais previsibilidade de captacao e uma rotina melhor para o comercial.",
    source: "website",
    landingPage: "/contato",
    utmSource: "google",
    utmMedium: "cpc",
    utmCampaign: "diagnostico-estetica",
    status: "PROPOSAL_SENT",
    tags: ["quente", "premium"],
    notes: "Fez reuniao e gostou do diagnostico.",
    estimatedTicket: 7000,
    ownerName: demoAdminUser.name,
    createdAt: "2026-03-10T13:30:00.000Z",
  },
  {
    id: "lead_2",
    name: "Rafael Pinto",
    email: "rafael@vistaimoveis.com",
    phone: "+55 21 97777-1111",
    company: "Vista Imoveis",
    niche: "Imobiliario",
    contactPreference: "WhatsApp",
    serviceInterest: "Web / Landing Pages",
    urgency: "imediata",
    objective: "Gerar leads para lancamento",
    source: "indicaÃ§Ã£o",
    status: "NEGOTIATION",
    tags: ["alto-ticket"],
    estimatedTicket: 15000,
    ownerName: demoAdminUser.name,
    createdAt: "2026-03-11T10:15:00.000Z",
  },
  {
    id: "lead_3",
    name: "Juliana Porto",
    email: "juliana@nutriforma.com",
    company: "NutriForma",
    niche: "Saude",
    contactPreference: "Email",
    serviceInterest: "Trafego Organico",
    urgency: "60-90-dias",
    objective: "Escalar vendas de programa online",
    source: "blog",
    status: "CONTACTED",
    tags: ["follow-up"],
    utmSource: "linkedin",
    utmCampaign: "insight-growth",
    estimatedTicket: 3000,
    ownerName: demoAdminUser.name,
    createdAt: "2026-03-15T17:10:00.000Z",
  },
];

export const demoClients: ClientRecord[] = [
  {
    id: "client_1",
    workspaceId: "workspace_1",
    name: "Henrique Dias",
    companyName: "Orion Imoveis",
    email: "henrique@orionimoveis.com",
    phone: "+55 21 98888-2222",
    niche: "Imobiliario",
    goals: "Gerar oportunidades qualificadas para empreendimentos premium",
    monthlyTicket: 6800,
    contractStatus: "ACTIVE",
    activeChannels: ["Email", "WhatsApp", "Meta Ads"],
    notes: "Valoriza clareza executiva e dashboard de acompanhamento.",
    websiteUrl: "https://orionimoveis.com.br",
    createdAt: "2026-01-22T09:00:00.000Z",
  },
  {
    id: "client_2",
    workspaceId: "workspace_1",
    name: "Patricia Luz",
    companyName: "Dermacare Prime",
    email: "patricia@dermacareprime.com",
    niche: "Estetica",
    goals: "Aumentar consultas para procedimentos de maior ticket",
    monthlyTicket: 5200,
    contractStatus: "ACTIVE",
    activeChannels: ["Email", "Google Ads"],
    createdAt: "2026-02-04T09:00:00.000Z",
  },
];

export const demoWorkspaces: WorkspaceRecord[] = [
  {
    id: "workspace_1",
    name: BRAND_COMPANY_NAME,
    slug: "ameni-digital-marketing",
    description: "Workspace central da agencia para comercial, operacao, criacao e entrega.",
    createdAt: "2026-01-02T09:00:00.000Z",
  },
];

export const demoProjects: ProjectRecord[] = [
  {
    id: "project_1",
    workspaceId: "workspace_1",
    workspaceName: BRAND_COMPANY_NAME,
    clientId: "client_1",
    clientName: "Orion Imoveis",
    ownerId: demoAdminUser.id,
    ownerName: demoAdminUser.name,
    name: "Onboarding e growth Q2",
    slug: "orion-onboarding-growth-q2",
    summary: "Projeto central de onboarding, campanhas, criativos e rotina comercial do cliente.",
    status: "ACTIVE",
    health: "ON_TRACK",
    startDate: "2026-03-01T09:00:00.000Z",
    endDate: "2026-05-30T18:00:00.000Z",
    taskCount: 4,
    completedTaskCount: 1,
    createdAt: "2026-03-01T09:00:00.000Z",
  },
  {
    id: "project_2",
    workspaceId: "workspace_1",
    workspaceName: BRAND_COMPANY_NAME,
    clientId: "client_2",
    clientName: "Dermacare Prime",
    ownerId: demoAccountManagerUser.id,
    ownerName: demoAccountManagerUser.name,
    name: "Sprint de conteudo e performance",
    slug: "dermacare-sprint-conteudo-performance",
    summary: "Operacao de social, video e paid com cadencia semanal.",
    status: "ACTIVE",
    health: "ATTENTION",
    startDate: "2026-03-04T09:00:00.000Z",
    endDate: "2026-04-30T18:00:00.000Z",
    taskCount: 2,
    completedTaskCount: 0,
    createdAt: "2026-03-04T09:00:00.000Z",
  },
];

export const demoProjectLists: ProjectListRecord[] = [
  {
    id: "list_1",
    projectId: "project_1",
    projectName: "Onboarding e growth Q2",
    name: "Intake e diagnostico",
    description: "Leitura inicial, reunioes e setup.",
    color: "#30b27c",
    order: 1,
    statusCatalog: ["Intake", "Em andamento", "Em revisao", "Concluido"],
    taskCount: 2,
    createdAt: "2026-03-01T09:00:00.000Z",
  },
  {
    id: "list_2",
    projectId: "project_1",
    projectName: "Onboarding e growth Q2",
    name: "Criacao e lancamento",
    description: "Campanhas, criativos e landing pages.",
    color: "#e0bb67",
    order: 2,
    statusCatalog: ["Briefing", "Produzindo", "Aprovacao", "Publicado"],
    taskCount: 2,
    createdAt: "2026-03-02T09:00:00.000Z",
  },
  {
    id: "list_3",
    projectId: "project_2",
    projectName: "Sprint de conteudo e performance",
    name: "Calendario editorial",
    description: "Planejamento, roteiro, gravacao e aprovacao.",
    color: "#66e1b1",
    order: 1,
    statusCatalog: ["Ideia", "Roteiro", "Edicao", "Aprovacao", "Publicado"],
    taskCount: 2,
    createdAt: "2026-03-04T09:00:00.000Z",
  },
];

export const demoProposals: ProposalRecord[] = [
  {
    id: "prop_1",
    title: "Retainer de performance Q2",
    summary: "Gestao de midia, CRO e IA comercial para acelerar o pipeline.",
    scope: "Meta Ads, Google Ads, landing pages e automacao comercial.",
    price: 6500,
    status: "SENT",
    leadId: "lead_1",
    leadName: "Luciana Araujo",
    validUntil: "2026-03-25T23:59:00.000Z",
    createdAt: "2026-03-12T15:20:00.000Z",
  },
  {
    id: "prop_2",
    title: "Sprint de funil de lancamento",
    summary: "Plano de 60 dias para captacao e qualificacao do lancamento.",
    scope: "Estrutura Meta, paginas, CRM e roteiros comerciais.",
    price: 9800,
    status: "DRAFT",
    clientId: "client_1",
    clientName: "Orion Imoveis",
    createdAt: "2026-03-14T08:00:00.000Z",
  },
];

export const demoTasks: TaskRecord[] = [
  {
    id: "task_1",
    title: "Revisar criativos da campanha de captacao",
    description: "Subir tres variacoes de angulo para fundo de funil.",
    status: "IN_PROGRESS",
    statusLabel: "Produzindo",
    priority: "HIGH",
    startDate: "2026-03-15T09:00:00.000Z",
    dueDate: "2026-03-18T17:00:00.000Z",
    estimatedMinutes: 180,
    trackedMinutes: 95,
    labels: ["Criativo", "Meta Ads"],
    workspaceId: "workspace_1",
    workspaceName: BRAND_COMPANY_NAME,
    projectId: "project_1",
    projectName: "Onboarding e growth Q2",
    listId: "list_2",
    listName: "Criacao e lancamento",
    ownerName: demoAdminUser.name,
    clientId: "client_1",
    clientName: "Orion Imoveis",
    assignees: [
      { id: demoAdminUser.id, name: demoAdminUser.name, email: demoAdminUser.email, role: demoAdminUser.role },
      { id: demoAccountManagerUser.id, name: demoAccountManagerUser.name, email: demoAccountManagerUser.email, role: demoAccountManagerUser.role },
    ],
    watchers: [{ id: "user_client_1", name: "Henrique Dias", email: "henrique@orionimoveis.com", role: "CLIENT" }],
    checklistProgress: { completed: 1, total: 3 },
    commentCount: 2,
    subtaskCount: 1,
    blockedByCount: 1,
    createdAt: "2026-03-15T11:00:00.000Z",
  },
  {
    id: "task_2",
    title: "Mandar follow-up da proposta",
    status: "TODO",
    statusLabel: "A fazer",
    priority: "MEDIUM",
    labels: ["Comercial"],
    workspaceId: "workspace_1",
    workspaceName: BRAND_COMPANY_NAME,
    projectId: "project_1",
    projectName: "Onboarding e growth Q2",
    listId: "list_1",
    listName: "Intake e diagnostico",
    leadId: "lead_1",
    leadName: "Luciana Araujo",
    assignees: [{ id: demoAdminUser.id, name: demoAdminUser.name, email: demoAdminUser.email, role: demoAdminUser.role }],
    watchers: [],
    checklistProgress: { completed: 0, total: 0 },
    commentCount: 1,
    subtaskCount: 0,
    blockedByCount: 0,
    createdAt: "2026-03-15T14:30:00.000Z",
  },
  {
    id: "task_3",
    title: "Estruturar landing page de captacao premium",
    description: "Definir bloco de prova, CTA principal e copy do hero.",
    status: "REVIEW",
    statusLabel: "Aprovacao",
    priority: "HIGH",
    startDate: "2026-03-13T09:00:00.000Z",
    dueDate: "2026-03-20T16:00:00.000Z",
    estimatedMinutes: 240,
    trackedMinutes: 220,
    labels: ["LP", "CRO"],
    workspaceId: "workspace_1",
    workspaceName: BRAND_COMPANY_NAME,
    projectId: "project_1",
    projectName: "Onboarding e growth Q2",
    listId: "list_2",
    listName: "Criacao e lancamento",
    clientId: "client_1",
    clientName: "Orion Imoveis",
    assignees: [{ id: demoAccountManagerUser.id, name: demoAccountManagerUser.name, email: demoAccountManagerUser.email, role: demoAccountManagerUser.role }],
    watchers: [{ id: demoAdminUser.id, name: demoAdminUser.name, email: demoAdminUser.email, role: demoAdminUser.role }],
    checklistProgress: { completed: 2, total: 2 },
    commentCount: 1,
    subtaskCount: 0,
    blockedByCount: 0,
    createdAt: "2026-03-13T10:00:00.000Z",
  },
  {
    id: "task_4",
    title: "Onboarding tecnico de tracking",
    description: "Checklist de pixels, eventos e UTMs do novo cliente.",
    status: "DONE",
    statusLabel: "Concluido",
    priority: "HIGH",
    startDate: "2026-03-10T09:00:00.000Z",
    endDate: "2026-03-12T15:00:00.000Z",
    estimatedMinutes: 120,
    trackedMinutes: 135,
    labels: ["Tracking", "Onboarding"],
    workspaceId: "workspace_1",
    workspaceName: BRAND_COMPANY_NAME,
    projectId: "project_1",
    projectName: "Onboarding e growth Q2",
    listId: "list_1",
    listName: "Intake e diagnostico",
    clientId: "client_1",
    clientName: "Orion Imoveis",
    assignees: [{ id: demoAdminUser.id, name: demoAdminUser.name, email: demoAdminUser.email, role: demoAdminUser.role }],
    watchers: [],
    checklistProgress: { completed: 4, total: 4 },
    commentCount: 0,
    subtaskCount: 0,
    blockedByCount: 0,
    createdAt: "2026-03-10T09:00:00.000Z",
  },
  {
    id: "task_5",
    title: "Roteiro dos reels da semana",
    description: "Preparar ganchos e CTA para conteudo short-form.",
    status: "IN_PROGRESS",
    statusLabel: "Roteiro",
    priority: "MEDIUM",
    startDate: "2026-03-16T09:30:00.000Z",
    dueDate: "2026-03-19T18:00:00.000Z",
    estimatedMinutes: 150,
    trackedMinutes: 60,
    labels: ["Conteudo", "Video"],
    workspaceId: "workspace_1",
    workspaceName: BRAND_COMPANY_NAME,
    projectId: "project_2",
    projectName: "Sprint de conteudo e performance",
    listId: "list_3",
    listName: "Calendario editorial",
    clientId: "client_2",
    clientName: "Dermacare Prime",
    assignees: [{ id: demoAccountManagerUser.id, name: demoAccountManagerUser.name, email: demoAccountManagerUser.email, role: demoAccountManagerUser.role }],
    watchers: [{ id: demoAdminUser.id, name: demoAdminUser.name, email: demoAdminUser.email, role: demoAdminUser.role }],
    checklistProgress: { completed: 0, total: 2 },
    commentCount: 1,
    subtaskCount: 0,
    blockedByCount: 0,
    createdAt: "2026-03-16T10:00:00.000Z",
  },
  {
    id: "task_6",
    title: "Ajustar headlines da LP",
    description: "Subtarefa focada no hero e na secao de prova social.",
    status: "TODO",
    statusLabel: "Briefing",
    priority: "MEDIUM",
    labels: ["Copy"],
    workspaceId: "workspace_1",
    workspaceName: BRAND_COMPANY_NAME,
    projectId: "project_1",
    projectName: "Onboarding e growth Q2",
    listId: "list_2",
    listName: "Criacao e lancamento",
    parentTaskId: "task_3",
    parentTaskTitle: "Estruturar landing page de captacao premium",
    clientId: "client_1",
    clientName: "Orion Imoveis",
    assignees: [{ id: demoAdminUser.id, name: demoAdminUser.name, email: demoAdminUser.email, role: demoAdminUser.role }],
    watchers: [],
    checklistProgress: { completed: 0, total: 0 },
    commentCount: 0,
    subtaskCount: 0,
    blockedByCount: 0,
    createdAt: "2026-03-16T11:00:00.000Z",
  },
];

export const demoTaskComments: TaskCommentRecord[] = [
  {
    id: "task_comment_1",
    taskId: "task_1",
    authorId: demoAdminUser.id,
    authorName: demoAdminUser.name,
    body: "Subi a primeira linha de criativos. @Caio pode validar se o gancho conversa com a landing?",
    mentions: ["Caio"],
    createdAt: "2026-03-15T15:30:00.000Z",
  },
  {
    id: "task_comment_2",
    taskId: "task_1",
    authorId: demoAccountManagerUser.id,
    authorName: demoAccountManagerUser.name,
    body: "Sim. Ajustaria apenas o frame de prova social para aproximar mais do ticket premium.",
    mentions: [],
    createdAt: "2026-03-15T16:05:00.000Z",
  },
  {
    id: "task_comment_3",
    taskId: "task_2",
    authorId: demoAdminUser.id,
    authorName: demoAdminUser.name,
    body: "Lead com boa aderencia. Fazer follow-up com CTA de reuniao ainda hoje.",
    mentions: [],
    createdAt: "2026-03-15T14:35:00.000Z",
  },
  {
    id: "task_comment_4",
    taskId: "task_5",
    authorId: demoAccountManagerUser.id,
    authorName: demoAccountManagerUser.name,
    body: "Precisamos alinhar os roteiros com o tema de autoridade da campanha da semana.",
    mentions: [],
    createdAt: "2026-03-16T12:00:00.000Z",
  },
];

export const demoTaskChecklistItems: TaskChecklistItemRecord[] = [
  {
    id: "task_check_1",
    taskId: "task_1",
    title: "Aprovar hooks de abertura",
    done: true,
    order: 1,
    assigneeId: demoAdminUser.id,
    assigneeName: demoAdminUser.name,
    createdAt: "2026-03-15T12:00:00.000Z",
  },
  {
    id: "task_check_2",
    taskId: "task_1",
    title: "Exportar versao 9:16",
    done: false,
    order: 2,
    assigneeId: demoAccountManagerUser.id,
    assigneeName: demoAccountManagerUser.name,
    dueDate: "2026-03-17T17:00:00.000Z",
    createdAt: "2026-03-15T12:10:00.000Z",
  },
  {
    id: "task_check_3",
    taskId: "task_1",
    title: "Publicar no board de aprovacao",
    done: false,
    order: 3,
    createdAt: "2026-03-15T12:20:00.000Z",
  },
  {
    id: "task_check_4",
    taskId: "task_3",
    title: "Definir CTA principal",
    done: true,
    order: 1,
    createdAt: "2026-03-14T11:00:00.000Z",
  },
  {
    id: "task_check_5",
    taskId: "task_3",
    title: "Revisar secao de prova",
    done: true,
    order: 2,
    createdAt: "2026-03-14T11:20:00.000Z",
  },
];

export const demoTaskDependencies: TaskDependencyRecord[] = [
  {
    id: "task_dep_1",
    taskId: "task_1",
    dependsOnTaskId: "task_3",
    dependsOnTaskTitle: "Estruturar landing page de captacao premium",
    createdAt: "2026-03-15T11:05:00.000Z",
  },
];

export const demoWorkTemplates: WorkTemplateRecord[] = [
  {
    id: "template_1",
    workspaceId: "workspace_1",
    name: "Onboarding de cliente premium",
    description: "Cria projeto com listas de intake, criacao, aprovacao e operacao inicial.",
    scope: "PROJECT",
    payload: {
      projectName: "Onboarding premium",
      lists: [
        { name: "Intake e diagnostico", statusCatalog: ["Intake", "Em andamento", "Concluido"] },
        { name: "Criacao e lancamento", statusCatalog: ["Briefing", "Produzindo", "Aprovacao", "Publicado"] },
        { name: "Operacao recorrente", statusCatalog: ["Planejado", "Em execucao", "Revisao", "Concluido"] },
      ],
    },
    createdAt: "2026-03-01T09:00:00.000Z",
  },
  {
    id: "template_2",
    workspaceId: "workspace_1",
    name: "Calendario editorial mensal",
    description: "Estrutura board de pauta, roteiro, gravacao, edicao e publicacao.",
    scope: "LIST",
    payload: {
      lists: [
        { name: "Ideias", statusCatalog: ["Ideia", "Selecionada"] },
        { name: "Producao", statusCatalog: ["Roteiro", "Gravacao", "Edicao"] },
        { name: "Publicacao", statusCatalog: ["Aprovacao", "Agendado", "Publicado"] },
      ],
    },
    createdAt: "2026-03-04T09:00:00.000Z",
  },
];

export const demoCustomFieldDefinitions: CustomFieldDefinitionRecord[] = [
  {
    id: "custom_field_1",
    workspaceId: "workspace_1",
    name: "Canal principal",
    key: "canal_principal",
    entityType: "PROJECT",
    fieldType: "SELECT",
    options: { values: ["Meta Ads", "Google Ads", "SEO", "Social Media", "Video"] },
    required: true,
    createdAt: "2026-03-01T09:00:00.000Z",
  },
  {
    id: "custom_field_2",
    workspaceId: "workspace_1",
    name: "SLA operacional",
    key: "sla_operacional",
    entityType: "TASK",
    fieldType: "NUMBER",
    options: null,
    required: false,
    createdAt: "2026-03-01T09:00:00.000Z",
  },
];

export const demoCustomFieldValues: CustomFieldValueRecord[] = [
  {
    id: "custom_value_1",
    definitionId: "custom_field_1",
    definitionName: "Canal principal",
    entityType: "PROJECT",
    entityId: "project_1",
    value: { selected: "Meta Ads" },
    createdAt: "2026-03-01T09:00:00.000Z",
  },
  {
    id: "custom_value_2",
    definitionId: "custom_field_2",
    definitionName: "SLA operacional",
    entityType: "TASK",
    entityId: "task_1",
    value: { minutes: 180 },
    createdAt: "2026-03-15T11:00:00.000Z",
  },
];

export const demoCampaigns: CampaignRecord[] = [
  {
    id: "camp_1",
    name: "Leads Meta - Condominio Vista",
    objective: "Gerar oportunidades para o lancamento premium",
    platform: "META",
    budget: 15000,
    status: "OPTIMIZING",
    metrics: {
      leads: 184,
      cpl: 49.2,
      ctr: "1.8%",
    },
    clientId: "client_1",
    clientName: "Orion Imoveis",
    createdAt: "2026-03-01T10:00:00.000Z",
  },
  {
    id: "camp_2",
    name: "Google Search - Harmonizacao",
    objective: "Captar pacientes para procedimento premium",
    platform: "GOOGLE",
    budget: 7800,
    status: "ACTIVE",
    metrics: {
      conversoes: 44,
      cpa: 82,
    },
    clientId: "client_2",
    clientName: "Dermacare Prime",
    createdAt: "2026-03-06T10:00:00.000Z",
  },
];

export const demoMessages: MessageRecord[] = [
  {
    id: "msg_1",
    subject: "Follow-up da proposta",
    body: "Oi Luciana, tudo bem? Passei para retomar a proposta enviada e entender se faz sentido alinharmos os proximos passos.",
    channel: "EMAIL",
    status: "DRAFT",
    recipientName: "Luciana Araujo",
    recipientEmail: "luciana@clinicabellavita.com",
    leadId: "lead_1",
    leadName: "Luciana Araujo",
    aiRequestId: "ai_1",
    scheduledFor: "2026-03-16T09:00:00.000Z",
    providerName: "mock-email",
    createdAt: "2026-03-15T15:10:00.000Z",
  },
  {
    id: "msg_2",
    subject: "Resumo da reuniao semanal",
    body: "Resumo: CPL estabilizou, proximo passo e testar nova promessa no anuncio e revisar segmentacao.",
    channel: "EMAIL",
    status: "SENT",
    recipientName: "Henrique Dias",
    recipientEmail: "henrique@orionimoveis.com",
    clientId: "client_1",
    clientName: "Orion Imoveis",
    providerName: "mock-email",
    providerMessageId: "provider-msg-1",
    sentAt: "2026-03-14T19:00:00.000Z",
    createdAt: "2026-03-14T18:55:00.000Z",
  },
];

export const demoFinancialRecords: FinancialRecord[] = [
  {
    id: "fin_1",
    title: "Mensalidade Ameni Digital Marketing - Marco",
    description: "Retainer mensal de performance e operacao comercial.",
    type: "INVOICE",
    status: "PENDING",
    amount: 6800,
    dueDate: "2026-03-20T00:00:00.000Z",
    reference: "INV-2026-003",
    clientId: "client_1",
    clientName: "Orion Imoveis",
    createdAt: "2026-03-01T09:00:00.000Z",
  },
  {
    id: "fin_2",
    title: "Mensalidade Dermacare - Fevereiro",
    type: "PAYMENT",
    status: "PAID",
    amount: 5200,
    paidAt: "2026-03-05T14:30:00.000Z",
    reference: "PAY-2026-014",
    clientId: "client_2",
    clientName: "Dermacare Prime",
    createdAt: "2026-03-05T14:30:00.000Z",
  },
];

export const demoAttachments: AttachmentRecord[] = [
  {
    id: "att_1",
    title: "Proposta comercial Q2",
    fileName: "proposta-q2.pdf",
    fileUrl: "https://example.com/proposta-q2.pdf",
    mimeType: "application/pdf",
    notes: "Versao enviada ao cliente para avaliacao.",
    clientId: "client_1",
    clientName: "Orion Imoveis",
    proposalId: "prop_2",
    proposalTitle: "Sprint de funil de lancamento",
    createdAt: "2026-03-14T09:15:00.000Z",
  },
];

export const demoAIRequests: AIRequestRecord[] = [
  {
    id: "ai_1",
    input: "Crie um follow-up consultivo da proposta enviada ha 3 dias.",
    objective: "Retomar a negociacao",
    tone: "consultivo",
    responseSize: "medio",
    mode: "SAVE_DRAFT",
    status: "GENERATED",
    generatedText:
      "Oi Luciana, tudo bem? Quis retomar a proposta para entender se fez sentido para o momento da clinica. Se achar util, posso resumir os proximos passos e o impacto esperado em agenda e previsibilidade.",
    leadId: "lead_1",
    leadName: "Luciana Araujo",
    createdAt: "2026-03-15T15:00:00.000Z",
  },
];

export const demoActivities: ActivityRecord[] = [
  {
    id: "log_1",
    action: "lead.created",
    entityType: "Lead",
    entityId: "lead_3",
    description: "Novo lead entrou pelo blog e foi atribuido para atendimento.",
    actorName: "Sistema",
    createdAt: "2026-03-15T17:12:00.000Z",
  },
  {
    id: "log_2",
    action: "ai.generated",
    entityType: "AIRequest",
    entityId: "ai_1",
    description: "IA gerou um follow-up consultivo e salvou como rascunho.",
    actorName: demoAdminUser.name,
    createdAt: "2026-03-15T15:05:00.000Z",
  },
  {
    id: "log_3",
    action: "campaign.optimized",
    entityType: "Campaign",
    entityId: "camp_1",
    description: "Atualizacao de criativos e redistribuicao de verba em conjunto com a equipe.",
    actorName: demoAdminUser.name,
    createdAt: "2026-03-14T16:40:00.000Z",
  },
];

export const demoDashboardSummary: DashboardSummary = {
  totalLeads: 38,
  activeClients: 12,
  openProposals: 6,
  pendingTasks: 9,
  runningCampaigns: 7,
  aiMessagesSent: 23,
  conversionRate: 32,
  estimatedRevenue: 84200,
};

export const demoUsers: UserRecord[] = [
  {
    id: demoAdminUser.id,
    name: demoAdminUser.name,
    email: demoAdminUser.email,
    role: demoAdminUser.role,
    createdAt: "2026-01-02T09:00:00.000Z",
  },
  {
    id: demoAccountManagerUser.id,
    name: demoAccountManagerUser.name,
    email: demoAccountManagerUser.email,
    role: demoAccountManagerUser.role,
    createdAt: "2026-01-05T10:00:00.000Z",
  },
  {
    id: "user_client_1",
    name: "Henrique Dias",
    email: "henrique@orionimoveis.com",
    role: "CLIENT",
    createdAt: "2026-01-22T09:00:00.000Z",
  },
];

export const demoAutomationSettings: AutomationSettingsRecord = {
  highIntentThreshold: 60,
  leadSlaImmediateHours: 2,
  leadSlaThirtyDaysHours: 6,
  leadSlaSixtyToNinetyDaysHours: 24,
  leadSlaPlanningHours: 48,
  leadSlaDefaultHours: 48,
  leadReminderDelayHours: 3,
  proposalFollowUpAfterDays: 3,
  proposalFollowUpChannel: "EMAIL",
  internalAlertRecipients: "admin@agencia-premium.com, comercial@atlasgrowth.studio",
};

export function createDemoSnapshot() {
  return {
    settings: structuredClone(demoSettings),
    services: structuredClone(demoServices),
    testimonials: structuredClone(demoTestimonials),
    caseStudies: structuredClone(demoCaseStudies),
    faqs: structuredClone(demoFaqs),
    blogPosts: structuredClone(demoBlogPosts),
    methodology: structuredClone(demoMethodologyContent),
    proofAssets: structuredClone(demoProofAssetsContent),
    sectorCatalog: structuredClone(defaultSectorCatalog),
    leads: structuredClone(demoLeads),
    clients: structuredClone(demoClients),
    workspaces: structuredClone(demoWorkspaces),
    projects: structuredClone(demoProjects),
    projectLists: structuredClone(demoProjectLists),
    proposals: structuredClone(demoProposals),
    tasks: structuredClone(demoTasks),
    taskComments: structuredClone(demoTaskComments),
    taskChecklistItems: structuredClone(demoTaskChecklistItems),
    taskDependencies: structuredClone(demoTaskDependencies),
    workTemplates: structuredClone(demoWorkTemplates),
    customFieldDefinitions: structuredClone(demoCustomFieldDefinitions),
    customFieldValues: structuredClone(demoCustomFieldValues),
    campaigns: structuredClone(demoCampaigns),
    messages: structuredClone(demoMessages),
    financialRecords: structuredClone(demoFinancialRecords),
    attachments: structuredClone(demoAttachments),
    aiRequests: structuredClone(demoAIRequests),
    activities: structuredClone(demoActivities),
    dashboardSummary: structuredClone(demoDashboardSummary),
    automationSettings: structuredClone(demoAutomationSettings),
    users: structuredClone(demoUsers),
  };
}

